server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/waste_platform?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
    username: root
    password: "12345"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true

app:
  jwt:
    secret: 2F0yq9N6mB4pZ1rX3nT8sU5vW6yA7bC8dE9fG0hI1jK2lM3nO4pQ5rS6tU7vW8x
    access-token-exp-minutes: 30
    refresh-token-exp-days: 14

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  level:
    org.springframework.security: INFO
